---
- name: install tomcat
  hosts: webservers
  become: true

  tasks:
    - name: install java 8
      yum:
        name: java-1.8.0-openjdk  # Adjust package name for Java 8
        state: installed

    - name: Downloading tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.88/bin/apache-tomcat-9.0.88.tar.gz
        dest: /opt
        mode: 0755

    - name: extracting packages
      unarchive:
        src: /opt/apache-tomcat-9.0.88.tar.gz
        dest: /opt
        remote_src: yes

    - name: changing permission
      file:
        path: /opt/apache-tomcat-9.0.88
        mode: 0755
        recurse: yes

    - name: start Tomcat using startup script
      command: ./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.88/bin

