---
- name: installing package
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: installing apache on RedHat
      yum:
        name: httpd
        state: present
      notify: start service 

    - name: starting apache on RedHat
      service:
        name: httpd
        state: started

    - name: copying httpd
      copy:
       src: index.html
       dest: /var/www/index.html

  handlers:
    - name: start service 
      service:
        name: httpd
        state: started 


