---
- name: install tomcat
  hosts: webservers
  become: true
  vars_files:
    - variable.yml
  tasks:
    - name: install java 8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Downloading tomcat
      get_url:
        url: '{{ tomcat_url }}'
        dest: /opt
        mode: '0755'

    - name: extracting packages
      unarchive:
        src: /opt/{{ tomcat_pkg }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: changing permission
      file:
        path: /opt/{{ tomcat_pkg }}
        mode: '0755'
        recurse: yes

    - name: creating links for tomcat startup
      file:
        src: /opt/{{ tomcat_pkg }}/bin/{{ item.tomcat_spt }}
        dest: /usr/local/bin/{{ item.cat_cmd }}
        state: link
      loop:
        - { tomcat_spt: startup.sh,  cat_cmd: tomcatup }
        - { tomcat_spt: shutdown.sh, cat_cmd: tomcatdown }
      notify: start tomcat

    - name: change port number
      copy:
        src: server.xml
        dest: '/opt/{{ tomcat_pkg }}/conf/server.xml'
      notify: restart tomcat

  handlers:
    - name: start tomcat
      shell: nohup /usr/local/bin/tomcatup

    - name: restart tomcat
      shell: nohup /usr/local/bin/tomcatdown; nohup /usr/local/bin/tomcatup

